 let size;
    size = 24;
    let increment = document.getElementById('bigger');
    let decrement = document.getElementById('smaller');
    
    
    
    document.getElementById('console').addEventListener('click', function(){
    
      console.log('One way to output content is through the web console');
    
    
    });
    
      document.getElementById('alert').addEventListener('click', function(){
    
      window.alert('Another way is through an alert box');
    
    
    });
    
        document.getElementById('html').addEventListener('click', function(){
    
      document.getElementById('output').innerHTML = "I am some new content generated by JS";
    
    
    });
    
    //var myVariable;//older JS convention
  
    
    increment.addEventListener("click",function(){
      //console.log("I'm clicked");
      size++;
      //console.log(size);
      document.getElementById('myP').style.fontSize= size +'px';
      
      
    });
    
    decrement.addEventListener("click", function() {
      size--;
      document.getElementById('myP').style.fontSize = size + 'px';
    });
    //document.getElementById('myP').style.color='purple';
    
    